### ISSUE TITLE
mouseDragged() & touchMoved() on touch enabled devices

### ISSUE THREAD

**Issue by ashishlijhara** [zenozeng/p5.js-svg#174]
Hello, I have been trying to get the mouseDragged/touchMoved on the touch enabled devices. This gets triggered as it should on desktop with a mouse, but if I were to use touch. The frequency at which these functions are invoked fairly decreases. Could anyone shed light or suggest a work around?

**Comment by zenozeng** [comment]
Sorry for my late relay. Mobile browsers apply a 300-350ms delay between touchend and click while they waited to see if this was going to be a double-tap or not, since double-tap was a gesture to zoom into text. you can use `touch-action: manipulation` to remove the 300-350ms tap delay.

```css
html {
    touch-action: manipulation;
}
```

https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away
